name:                ulambdac
version:             0.1.0.0
github:              "Luc-Saccoccio/ulambdac"
license:             MIT
author:              "Luc Saccoccio--Le Guennec"
maintainer:          "lucsaccoccio@disroot.org"
copyright:           "2023 Luc Saccoccio--Le Guennec"

extra-source-files:
- README.md

# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/Luc-Saccoccio/ulambdac#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
      - Eval
      - Def
      - Parser
  dependencies:
  - text
  - megaparsec
  - unordered-containers
  - hashable

executables:
  ulambdac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ulambdac
    - isocline
    - megaparsec
    - unordered-containers
